[build]
builder = "dockerfile"

[deploy]

[service.server]
port = 3001

[service.postgres]
image = "postgres:16"

[service.postgres.config]
POSTGRES_USER = "falsisters"
POSTGRES_DB = "falsisters"

[service.minio]
image = "minio/minio:latest"

[service.minio.config]
MINIO_ROOT_USER = "falsisters"
MINIO_BROWSER = "on"

[service.minio.command]
args = ["server", "/data", "--console-address", ":9001"]
